### ISSUE TITLE
Add instructions to set up Ruby instance locally 

### ISSUE THREAD

**Issue by abhi12ravi** [fayepal/fsa-training#40]
Request from @viswanathamsantosh  [here](https://github.com/fayetandog/fsa-training/commit/df9633f78a0c0a1aa7e912fad6a7bc924ca46863#commitcomment-14927131)

**Comment by devcer** [comment]
@birajkarmakar did you tried this?

**Comment by anistuhin** [comment]
Guys do you need how to??

**Comment by anistuhin** [comment]
Check this one http://jekyllrb.com/docs/installation/

**Comment by abhi12ravi** [comment]
@anistuhin Did it work out? Were you able to set up the environment locally?

**Comment by anistuhin** [comment]
No, I didn't as I use Windows. I forked the repo and edited inside GitHub while editing. I can give it a try in Windows and then let you know. I might then add the instructions inside README :)

**Comment by abhi12ravi** [comment]
That would be great! Thank you.

**Comment by fayepal** [comment]
Learning how to do it through [this tutorial](http://jekyll-windows.juthilo.com/) but when I am done with the set-up and trying to preview the site I am stuck with this kind of error

```
C:\Sites>jekyll serve --watch
Configuration file: none
            Source: C:/Sites
       Destination: C:/Sites/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Included file '_includes/category_gallery.html' not found in
 C:/Sites/fsa-training/modules/conflict management/_posts/2000-01-03-moztour.mar
kdown
jekyll 3.0.1 | Error:  Included file '_includes/category_gallery.html' not found
```

Tried deleting all the modules to see if this will run without them but then it always finds a file that is 'not found'. Weird, the files mentioned are all in the folder. :disappointed:

**Comment by devcer** [comment]
@anistuhin worked in windows as well! thanks. :)

**Comment by abhi12ravi** [comment]
Did someone try hosting it on Linux? I get the following error when I run `jekyll serve`

Paste bin link: https://pastebin.mozilla.org/8858902
However, I am able to successful to host the [P2P template repo](https://github.com/p2pu/course-in-a-box) on my machine. Weird!
@fayetandog Were you able to resolve the issue indicated above?

**Comment by fayepal** [comment]
@abhi12ravi No, I haven't resolved the issue yet :(
