### ISSUE TITLE
Create a dropdown menu for the Activities To Do and Skills Training module groups

### ISSUE THREAD

**Issue by fayepal** [fayepal/fsa-training#41]
Hey everyone, need help creating a dropdown for the said pathways. Under them are the following modules:

Activities To Do
*Online activity kits
*Introduction session kit
*Offline Activity Kits
*Recognition System Dive

Skills training
*Communication etiquette
*Public Speaking
*Conflict Management
*Developer Resources

**Comment by anistuhin** [comment]
Hi, i have worked on this and got it done: http://anistuhin.github.io/fsa-training/
But to implement the navigation perfectly and make it easy for future edits or alters i need you to answer the following questions:
1. Do you want to include pages as well as courses in the navigation or only the courses?? Currently all the navigation elements are course, i see. Moreover, for the dropdown you wanted to create will follow the same mechanism while incorporating both pages and courses in navigation.
2. When you click on 'Start a club' or 'Things you'll need' (i mean any course) you can see that on top lest corner and right bottom of the main content area shows navigation to previous or next course. So, do you want all the courses throughout he whole site should be connected to each other like this?? If yes, then comment the order of the courses here :)

So, after you clear those two things, i will make some edits based on your answer and then send you the pull request :)

Thanks.

**Comment by anistuhin** [comment]
btw on the previous comment by 'courses' i meant 'modules' in terms of our discussion :P and by 'pages' this template refers to plain pages but 'not modules'

**Comment by fayepal** [comment]
1.) Realized I forgot to provide an important example: http://education.mozilla-community.org/
I was thinking to do exactly that, the dropdown contains the modules.
2.) The module navigation's order can easily be set by naming the section files inside the module's folders, so no need to set it up manually.

Thanks for helping out on this! :smile:

**Comment by anistuhin** [comment]
The module navigation's order can't be set by naming the section files :P Check the attached image for this :) ![untitled-1](https://cloud.githubusercontent.com/assets/8442003/12003519/8c028eda-ab4d-11e5-80b2-0aa916565147.gif) We can change the the order anytime :P It's two minutes work.

So, it's done. Created pull request. Check the preview here: http://anistuhin.github.io/fsa-training/ and if everything's fine, then merge :)

**Comment by anistuhin** [comment]
Btw don't you think we should add "tabzilla" also removing that "p2pu toggle menu"??

**Comment by fayepal** [comment]
Oh okay I thought you were talking about the sections in the module :stuck_out_tongue_closed_eyes: 
Awesome awesome! Merging it.
YES adding Tabzilla and removing the toggle menu is needed. :)
Thanks!

**Comment by anistuhin** [comment]
Done, sent pull.

**Comment by anistuhin** [comment]
sent the pull request for tabzilla, 4 days ago ;)

**Comment by fayepal** [comment]
Sorry, got caught up with the holiday. :stuck_out_tongue_closed_eyes:  Thanks for the help on this Anis!
